# Generated by Django 4.1 on 2022-10-11 06:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_title', models.CharField(max_length=50)),
                ('News_dis', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_title', models.CharField(max_length=50)),
                ('mod_dis', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_title1', models.CharField(max_length=30)),
                ('trend_title2', models.CharField(max_length=30)),
                ('trend_title3', models.CharField(max_length=30)),
                ('trend_title4', models.CharField(max_length=30)),
                ('trend_title5', models.CharField(max_length=30)),
            ],
        ),
    ]
